# Практическое занятие 02. Минимум Python, NumPy, pandas

Цель занятия: научиться читать и писать простой код на Python, а численные расчёты и таблицы переносить на NumPy и pandas — без циклов там, где есть векторная операция.

План:

- Jupyter-блокноты: горячие клавиши, магические команды — 5 мин;
- Python: типы данных, коллекции, функции, классы — 20 мин;
- NumPy: массивы, срезы и маски, векторизация, транслирование — 15 мин;
- pandas: `Series`, `DataFrame`, фильтрация, `groupby` — 15 мин;
- задание: обработка таблицы погоды — 20 мин.

# Jupyter-блокноты

Блокнот (англ. *notebook*) — документ из ячеек двух видов: **код** (выполняется ядром Python, результат последнего выражения выводится под ячейкой) и **Markdown** (текст, формулы, картинки). Переменные живут в ядре, поэтому важен **порядок выполнения** ячеек, а не порядок их расположения: номер `[N]` слева показывает, какой по счёту выполнилась ячейка.

Документация:

- [Project Jupyter](https://docs.jupyter.org/en/latest/) — общая документация;
- [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) и [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/) — интерфейсы;
- [Магические команды IPython](https://ipython.readthedocs.io/en/stable/interactive/magics.html).

## Горячие клавиши

У блокнота два режима: **редактирования** (курсор внутри ячейки, `Enter`) и **командный** (ячейка выделена рамкой, `Esc`).

| Клавиши | Режим | Действие |
|---|---|---|
| `Shift + Enter` | любой | выполнить ячейку и перейти к следующей |
| `Ctrl + Enter` | любой | выполнить ячейку и остаться на ней |
| `Alt + Enter` | любой | выполнить ячейку и вставить новую ниже |
| `Esc` / `Enter` | — | перейти в командный режим / в режим редактирования |
| `A` / `B` | командный | вставить ячейку выше / ниже |
| `D, D` | командный | удалить ячейку |
| `Z` | командный | отменить удаление ячейки |
| `M` / `Y` | командный | сделать ячейку Markdown / кодом |
| `0, 0` | командный | перезапустить ядро |
| `Tab` | редактирования | автодополнение |
| `Shift + Tab` | редактирования | подсказка по функции под курсором |
| `Ctrl + /` | редактирования | закомментировать строки |

## Магические команды

Команды IPython, которые не являются кодом Python:

- `%команда` — строковая магия, действует на одну строку;
- `%%команда` — магия ячейки, действует на всю ячейку и пишется первой строкой;
- `!команда` — выполнить команду оболочки;
- `объект?` — справка по объекту.

| Команда | Действие |
|---|---|
| `%lsmagic` | список всех магических команд |
| `%time`, `%%time` | время одного выполнения |
| `%timeit`, `%%timeit` | среднее время многих выполнений |
| `%who`, `%whos` | переменные в ядре |
| `%pwd` | текущий каталог |
| `%pip install <пакет>` | установить пакет в окружение ядра |
| `%matplotlib inline` | графики matplotlib внутри блокнота |

In [1]:
%time total = sum(range(1_000_000))

CPU times: user 8.9 ms, sys: 84 µs, total: 8.98 ms
Wall time: 8.38 ms

In [2]:
%timeit -n 10 -r 3 sum(range(1_000_000))

7.49 ms ± 229 µs per loop (mean ± std. dev. of 3 runs, 10 loops each)

In [3]:
%%time
squares = [i ** 2 for i in range(1_000_000)]
len(squares)

CPU times: user 160 ms, sys: 7.95 ms, total: 168 ms
Wall time: 166 ms

1000000

In [4]:
%who

squares	 total

In [5]:
%pwd

'/home/danil/Personal/mamo-fall-2026/practices/02-python-data-stack'

In [6]:
import sys

sys.version

'3.8.10 (default, Jun 22 2022, 20:18:18) \n[GCC 9.4.0]'

Версия интерпретатора ядра: блокнот выполняется тем Python, на котором запущено ядро, а не тем, что вызывается в терминале командой `python`.

# Python

Основа этого раздела — курс Computer Science Center [«Программирование на Python»](https://compscicenter.ru/courses/python/2015-autumn/) (осень 2015, лектор — Сергей Лебедев). У каждой лекции есть видеозапись и слайды. Для этого занятия:

- [Лекция 1. Начало](https://compscicenter.ru/courses/python/2015-autumn/classes/1364/) — типы данных и управляющие конструкции;
- [Лекция 2. Всё, что вы хотели знать о функциях в Python](https://compscicenter.ru/courses/python/2015-autumn/classes/1386/);
- [Лекция 5. Встроенные коллекции и модуль collections](https://compscicenter.ru/courses/python/2015-autumn/classes/1476/);
- [Лекция 6. Классы 1](https://compscicenter.ru/courses/python/2015-autumn/classes/1477/);
- [Лекция 12. Быстрее, Python, ещё быстрее](https://compscicenter.ru/courses/python/2015-autumn/classes/1561/) — в том числе NumPy.

Примеры курса написаны под Python 3.4–3.5; всё, что в них есть, работает и в современных версиях.

## Основные типы данных

- `int` — целые числа произвольной длины;
- `float` — числа с плавающей точкой;
- `bool` — логические значения `True` и `False`;
- `str` — строки (неизменяемые последовательности символов);
- `None` — «ничего», единственный объект типа `NoneType`.

In [7]:
type(42), type(3.14), type(True), type('hello'), type(None)

(int, float, bool, str, NoneType)

Целые числа в Python не переполняются:

In [8]:
2 ** 100

1267650600228229401496703205376

А вот числа с плавающей точкой хранятся приближённо:

In [9]:
0.1 + 0.2 == 0.3

False

In [10]:
abs((0.1 + 0.2) - 0.3) < 1e-9

True

Деление: `/` всегда возвращает `float`, `//` — целочисленное деление, `%` — остаток.

In [11]:
7 / 2, 7 // 2, 7 % 2

(3.5, 3, 1)

`bool` — подкласс `int`, поэтому `True` ведёт себя как `1`:

In [12]:
True + True, isinstance(True, int)

(2, True)

Строки: срезы, методы, f-строки.

In [13]:
name = 'Python'  # срезы строки: [start:stop:step]
version = 3.8

name[0], name[-1], name[::-1], name.upper(), f'{name} {version}'

('P', 'n', 'nohtyP', 'PYTHON', 'Python 3.8')

## Изменяемые и неизменяемые объекты

- **неизменяемые** (англ. *immutable*): `int`, `float`, `bool`, `str`, `tuple`, `None` — любая «модификация» создаёт новый объект;
- **изменяемые** (англ. *mutable*): `list`, `dict`, `set` — меняются на месте.

Переменная в Python — это имя, которое ссылается на объект. Функция `id()` возвращает идентификатор объекта. В стандартной реализации Python (CPython) заранее создаются объекты целых чисел от −5 до 256. Кэширование небольших целых чисел — это оптимизация CPython, позволяющая экономить память и время на создании часто используемых объектов.

In [14]:
x = 13  # связываем переменную x с объектом целого числа 13

id(13), id(x), id(13) == id(x)

(9801632, 9801632, True)

В то же время для больших чисел:

In [15]:
x = int('1000')
y = int('1000')
# значения равны, но это разные объекты
x == y, x is y

(True, False)

In [16]:
text = 'abc'
text_id = id(text)
text += 'd'

text, id(text) == text_id

('abcd', False)

In [17]:
items = [1, 2, 3]
items_id = id(items)
items += [4]

items, id(items) == items_id

([1, 2, 3, 4], True)

Два имени могут ссылаться на один и тот же изменяемый объект — изменение через одно имя видно через другое:

In [18]:
first = [1, 2, 3]
second = first
second.append(4)

first, first is second

([1, 2, 3, 4], True)

In [19]:
third = first.copy()  # Явная копия — новый объект
third.append(5)

first, third

([1, 2, 3, 4], [1, 2, 3, 4, 5])

## Коллекции

### Список (`list`)

Упорядоченная изменяемая последовательность.

In [20]:
numbers = [5, 3, 8, 1]
numbers.append(10)
numbers[0] = 0

numbers, len(numbers)

([0, 3, 8, 1, 10], 5)

Срезы `[start:stop:step]` — `stop` не включается:

In [21]:
numbers = list(range(10))  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numbers[2:5], numbers[:3], numbers[-3:], numbers[::2]

([2, 3, 4], [0, 1, 2], [7, 8, 9], [0, 2, 4, 6, 8])

### Кортеж (`tuple`)

Упорядоченная **неизменяемая** последовательность. Часто используется для возврата нескольких значений и распаковки.

In [22]:
point = (3, 4)
x, y = point

x, y

(3, 4)

In [23]:
try:
    point[0] = 10
except TypeError as error:
    print(error)

'tuple' object does not support item assignment

### Множество (`set`)

Неупорядоченный набор **уникальных** элементов, проверка `in` — за O(1).

In [24]:
letters = set('abracadabra')
letters

{'a', 'b', 'c', 'd', 'r'}

In [25]:
first = {1, 2, 3, 4}
second = {3, 4, 5}

first | second, first & second, first - second

({1, 2, 3, 4, 5}, {3, 4}, {1, 2})

### Словарь (`dict`)

Отображение «ключ → значение»; ключи — неизменяемые объекты. С Python 3.7 сохраняет порядок вставки.

In [26]:
ages = {'Анна': 20, 'Борис': 21}
ages['Вера'] = 19

ages

{'Анна': 20, 'Борис': 21, 'Вера': 19}

In [27]:
ages['Анна'], ages.get('Глеб'), ages.get('Глеб', 0)

(20, None, 0)

In [28]:
for name, age in ages.items():
    print(f'{name}: {age}')

Анна: 20
Борис: 21
Вера: 19

### Когда что выбирать

| Коллекция | Порядок | Изменяемая | Дубликаты | Типичный случай |
|---|---|---|---|---|
| `list` | да | да | да | последовательность однотипных элементов |
| `tuple` | да | нет | да | запись фиксированной длины, ключ словаря |
| `set` | нет | да | нет | уникальные элементы, быстрая проверка `in` |
| `dict` | да (вставки) | да | ключи — нет | поиск значения по ключу |

### Включения (англ. *comprehensions*)

Короткий способ построить коллекцию из другой коллекции.

In [29]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
squares = [i ** 2 for i in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [31]:
even_squares = [i ** 2 for i in range(10) if i % 2 == 0]
even_squares

[0, 4, 16, 36, 64]

In [32]:
word_lengths = {word: len(word) for word in ['кот', 'собака', 'ёж']}
word_lengths

{'кот': 3, 'собака': 6, 'ёж': 2}

In [33]:
[i % 3 for i in range(10)]

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0]

In [34]:
{i % 3 for i in range(10)}

{0, 1, 2}

## Функции

### Базовый синтаксис

Функция объявляется через `def`, возвращает значение через `return`. Без `return` функция возвращает `None`.

In [35]:
def circle_area(radius):
    """Вычисляет площадь круга."""
    return 3.14159 * radius ** 2


circle_area(2)

12.56636

### Позиционные и именованные аргументы, значения по умолчанию

In [36]:
def greet(name, greeting='Привет'):
    return f'{greeting}, {name}!'


greet('Анна'), greet('Анна', 'Здравствуйте'), greet(greeting='Добрый день', name='Борис')

('Привет, Анна!', 'Здравствуйте, Анна!', 'Добрый день, Борис!')

### Ловушка: изменяемое значение по умолчанию

Значение по умолчанию вычисляется **один раз** — при объявлении функции. Если это список, все вызовы делят один и тот же объект.

In [37]:
def append_item(item, items=[]):
    items.append(item)
    return items

In [38]:
append_item(1)

[1]

In [39]:
append_item(2)

[1, 2]

Правильный способ — `None` по умолчанию и создание объекта внутри функции:

In [40]:
def append_item(item, items=None):
    if items is None:
        items = []
    items.append(item)
    return items


append_item(1), append_item(2)

([1], [2])

### Функция как аргумент: `sorted(key=...)` и `lambda`

Функции в Python — обычные объекты: их можно передавать в другие функции. `lambda` — короткая анонимная функция из одного выражения.

In [41]:
def get_second_item(x):
    """Функция возвращает второй (нумерация с нуля) элемент коллекции."""
    return x[1]

In [42]:
students = [('Вера', 22), ('Борис', 18), ('Анна', 20)]

sorted(students)

[('Анна', 20), ('Борис', 18), ('Вера', 22)]

In [43]:
sorted(students, key=get_second_item)  # выполняем сортировку по возрасту

[('Борис', 18), ('Анна', 20), ('Вера', 22)]

То же самое можно выполнить при помощи `lambda`-функции:

In [44]:
sorted(students, key=lambda x: x[1])

[('Борис', 18), ('Анна', 20), ('Вера', 22)]

In [45]:
sorted(['banana', 'Apple', 'cherry'], key=lambda x: x.lower())

['Apple', 'banana', 'cherry']

In [46]:
max(students, key=lambda student: student[1])

('Вера', 22)

## Классы

Класс объединяет данные (атрибуты) и поведение (методы). Метод `__init__` вызывается при создании объекта, `self` — ссылка на сам объект.

In [47]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def distance_to(self, other):
        return ((self.x - other.x) ** 2 + (self.y - other.y) ** 2) ** 0.5


start = Point(0, 0)
end = Point(3, 4)

start.distance_to(end)

5.0

In [48]:
start

### [`@dataclass`](https://docs.python.org/3/library/dataclasses.html)

Для классов, которые в основном хранят данные, `@dataclass` сам генерирует `__init__`, `__repr__` и `__eq__` по аннотациям полей.

In [49]:
from dataclasses import dataclass


@dataclass
class Point:
    x: float
    y: float

    def distance_to(self, other):
        return ((self.x - other.x) ** 2 + (self.y - other.y) ** 2) ** 0.5


start = Point(0, 0)
end = Point(3, 4)

start, start.distance_to(end), Point(1, 2) == Point(1, 2)

(Point(x=0, y=0), 5.0, True)

# [NumPy](https://numpy.org/)

Список Python хранит ссылки на отдельные объекты, разбросанные по памяти. Массив NumPy хранит числа одного типа в непрерывном блоке памяти — поэтому операции над ним выполняются в скомпилированном коде во много раз быстрее.

![](https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/8a34a4f653bdbdc01415a94dc20d4e9b97438965/notebooks/figures/array_vs_list.png)

Литература по NumPy и pandas: Джейк Вандер Плас. [Python для сложных задач: наука о данных и машинное обучение](https://www.piter.com/collection/python/product/python-dlya-slozhnyh-zadach-nauka-o-dannyh-i-mashinnoe-obuchenie-2). — СПб.: Питер (серия «Бестселлеры O'Reilly»). NumPy — глава 2, pandas — глава 3. Оригинал книги в открытом доступе: [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/); иллюстрации этого блокнота взяты оттуда.

In [50]:
# pip3 install numpy
import numpy as np

np.__version__

'1.24.4'

## [Создание массивов](https://numpy.org/doc/stable/reference/routines.array-creation.html)

- `np.array` — массив из списка Python;
- `np.zeros`, `np.ones` — массив заданной формы, заполненный `0` или `1`;
- `np.arange` — аналог `range`;
- `np.linspace` — `num` равноотстоящих точек на отрезке.

In [51]:
x = np.array([1, 2, 3])
x, x.dtype

(array([1, 2, 3]), dtype('int64'))

У массива один тип данных `dtype` на все элементы — при смешивании типов NumPy приводит их к общему:

In [52]:
np.array([1, 2.5, 3]).dtype

dtype('float64')

In [53]:
np.zeros(shape=(2, 3), dtype=np.uint8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [54]:
np.arange(0, 10, 2), np.linspace(0, 1, 5)

(array([0, 2, 4, 6, 8]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

## Атрибуты массива

In [55]:
rng = np.random.default_rng(seed=42)
matrix = rng.integers(0, 10, size=(3, 4))

matrix

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]])

In [56]:
matrix.ndim, matrix.shape, matrix.size, matrix.dtype

(2, (3, 4), 12, dtype('int64'))

## Срезы и маски

Срезы работают как в списках, но по каждой оси через запятую: `[строки, столбцы]`.

In [57]:
matrix[0], matrix[:, 1], matrix[:2, 1:3]

(array([0, 7, 6, 4]),
 array([7, 8, 0]),
 array([[7, 6],
        [8, 0]]))

Сравнение массива с числом даёт **булеву маску** той же формы; маской можно выбирать элементы:

In [58]:
matrix > 5

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [False, False, False,  True]])

In [59]:
matrix[matrix > 5]

array([7, 6, 8, 6, 9])

In [60]:
values = np.arange(10)

values[(values > 2) & (values % 2 == 0)]  # Для масок — & и |, а не and и or

array([4, 6, 8])

## Векторизация

Посчитаем сумму квадратов миллиона чисел — циклом Python и векторной операцией NumPy.

In [61]:
values = rng.random(1_000_000)
values_list = list(values)

In [62]:
%%timeit -n 3 -r 3
total = 0.0
for value in values_list:
    total += value ** 2

97.5 ms ± 1.05 ms per loop (mean ± std. dev. of 3 runs, 3 loops each)

In [63]:
%%timeit -n 3 -r 3
total = (values ** 2).sum()

1.23 ms ± 354 µs per loop (mean ± std. dev. of 3 runs, 3 loops each)

Векторная операция быстрее на два порядка. Правило: **если есть векторная операция — цикл не нужен**.

## Агрегаты по осям

- `axis=0` — сворачиваем строки, результат по каждому столбцу;
- `axis=1` — сворачиваем столбцы, результат по каждой строке.

In [64]:
matrix

array([[0, 7, 6, 4],
       [4, 8, 0, 6],
       [2, 0, 5, 9]])

In [65]:
matrix.sum(), matrix.sum(axis=0), matrix.mean(axis=1)

(51, array([ 6, 15, 11, 19]), array([4.25, 4.5 , 4.  ]))

In [66]:
matrix.min(), matrix.max(axis=0), matrix.argmax(axis=1)

(0, array([4, 8, 6, 9]), array([1, 1, 3]))

## [Транслирование (англ. *broadcasting*)](https://numpy.org/doc/stable/user/basics.broadcasting.html)

Операции над массивами разной формы: меньший массив «растягивается» вдоль недостающих осей. Формы сравниваются с конца, размеры должны совпадать или равняться 1.

![](https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/8a34a4f653bdbdc01415a94dc20d4e9b97438965/notebooks/figures/02.05-broadcasting.png)

In [67]:
np.arange(3) + 5

array([5, 6, 7])

In [68]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [69]:
np.arange(3).reshape(3, 1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Типичный пример — центрирование данных: вычитаем из каждого столбца его среднее.

In [70]:
data = rng.normal(loc=10, scale=2, size=(5, 3))
centered = data - data.mean(axis=0)

centered.mean(axis=0).round(10)

array([ 0., -0.,  0.])

## Матричное умножение `@`

`*` — поэлементное умножение, `@` — матричное.

In [71]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

a * b

array([[ 5, 12],
       [21, 32]])

In [72]:
a @ b

array([[19, 22],
       [43, 50]])

In [73]:
weights = np.array([0.5, -1.0])

a @ weights

array([-1.5, -2.5])

# [pandas](https://pandas.pydata.org/)

pandas построен поверх NumPy и добавляет к массивам **индекс** и **имена столбцов** — получается таблица.

- `pd.Series` — одномерный массив с индексом;
- `pd.DataFrame` — таблица: набор `Series` с общим индексом.

Литература: Джейк Вандер Плас. [Python для сложных задач: наука о данных и машинное обучение](https://www.piter.com/collection/python/product/python-dlya-slozhnyh-zadach-nauka-o-dannyh-i-mashinnoe-obuchenie-2), глава 3.

In [74]:
# pip3 install pandas
import pandas as pd

pd.__version__

'2.0.3'

## Series

In [75]:
population = pd.Series({'Тюмень': 850, 'Омск': 1110, 'Томск': 570, 'Курган': 300})
population

Тюмень     850
Омск      1110
Томск      570
Курган     300
dtype: int64

In [76]:
population.index, population.values

(Index(['Тюмень', 'Омск', 'Томск', 'Курган'], dtype='object'),
 array([ 850, 1110,  570,  300]))

In [77]:
population['Тюмень'], population[population > 600]

(850,
 Тюмень     850
 Омск      1110
 dtype: int64)

## DataFrame

In [78]:
area = pd.Series({'Тюмень': 698, 'Омск': 567, 'Томск': 297, 'Курган': 392})
cities = pd.DataFrame({'population': population, 'area': area})

cities

        population  area
Тюмень         850   698
Омск          1110   567
Томск          570   297
Курган         300   392

Столбец — это `Series`. Обращение к столбцам — только через квадратные скобки `df['col']`:

In [79]:
cities['area']

Тюмень    698
Омск      567
Томск     297
Курган    392
Name: area, dtype: int64

In [80]:
cities[['population', 'area']]

        population  area
Тюмень         850   698
Омск          1110   567
Томск          570   297
Курган         300   392

## Индексаторы `loc` и `iloc`

- `loc` — по меткам индекса;
- `iloc` — по позициям, как в NumPy.

In [81]:
cities.loc['Омск'], cities.iloc[0, 1]

(population    1110
 area           567
 Name: Омск, dtype: int64,
 698)

In [82]:
cities.loc['Тюмень':'Томск', 'area']

Тюмень    698
Омск      567
Томск     297
Name: area, dtype: int64

## Новый столбец, фильтрация, сортировка

Операции над столбцами векторизованы так же, как в NumPy.

In [83]:
cities['density'] = cities['population'] * 1000 / cities['area']
cities

        population  area      density
Тюмень         850   698  1217.765043
Омск          1110   567  1957.671958
Томск          570   297  1919.191919
Курган         300   392   765.306122

In [84]:
cities[cities['density'] > 1500]

       population  area      density
Омск         1110   567  1957.671958
Томск         570   297  1919.191919

In [85]:
cities[(cities['population'] > 500) & (cities['area'] < 600)]

       population  area      density
Омск         1110   567  1957.671958
Томск         570   297  1919.191919

In [86]:
cities.sort_values('density', ascending=False)

        population  area      density
Омск          1110   567  1957.671958
Томск          570   297  1919.191919
Тюмень         850   698  1217.765043
Курган         300   392   765.306122

## Чтение CSV и первый взгляд на данные

Создадим небольшой CSV-файл и прочитаем его через [`pd.read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html).

In [87]:
from pathlib import Path

data_dir = Path('data')  # Файлы, которые создаёт блокнот, не хранятся в git
data_dir.mkdir(exist_ok=True)

students_path = data_dir / 'students.csv'
students_path.write_text(
    'name,group,math,python\n'
    'Анна,ПИ-1,5,4\n'
    'Борис,ПИ-1,3,5\n'
    'Вера,ПИ-2,4,5\n'
    'Глеб,ПИ-2,5,3\n'
    'Дина,ПИ-2,,4\n',
    encoding='utf-8',
)

students = pd.read_csv(students_path)
students

    name group  math  python
0   Анна  ПИ-1   5.0       4
1  Борис  ПИ-1   3.0       5
2   Вера  ПИ-2   4.0       5
3   Глеб  ПИ-2   5.0       3
4   Дина  ПИ-2   NaN       4

In [88]:
students.head(3)

    name group  math  python
0   Анна  ПИ-1   5.0       4
1  Борис  ПИ-1   3.0       5
2   Вера  ПИ-2   4.0       5

In [89]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   group   5 non-null      object
 2   math    4 non-null      float64
 3   python  5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 288.0+ bytes

In [90]:
students.describe()

           math   python
count  4.000000  5.00000
mean   4.250000  4.20000
std    0.957427  0.83666
min    3.000000  3.00000
25%    3.750000  4.00000
50%    4.500000  4.00000
75%    5.000000  5.00000
max    5.000000  5.00000

## Пропущенные значения

Пустая ячейка CSV стала `NaN`. Агрегаты pandas по умолчанию их пропускают.

In [91]:
students.isna().sum()

name      0
group     0
math      1
python    0
dtype: int64

In [92]:
students['math'].mean(), students['math'].fillna(0).mean()

(4.25, 3.4)

## Группировка `groupby`

Схема «разделить — применить — объединить» (англ. *split — apply — combine*): разбиваем таблицу на группы по значению столбца, считаем агрегат в каждой группе, собираем результат.

![](https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/8a34a4f653bdbdc01415a94dc20d4e9b97438965/notebooks/figures/03.08-split-apply-combine.png)

In [93]:
students.groupby('group')['python'].mean()

group
ПИ-1    4.5
ПИ-2    4.0
Name: python, dtype: float64

In [94]:
students.groupby('group')[['math', 'python']].agg(['mean', 'max'])

      math      python
      mean  max   mean max
group
ПИ-1   4.0  5.0    4.5   5
ПИ-2   4.5  5.0    4.0   5

In [95]:
students.groupby('group').size()

group
ПИ-1    2
ПИ-2    3
dtype: int64

# Задание: погода

Ниже генерируется таблица ежедневных наблюдений погоды в нескольких городах за 2025 год и сохраняется в `data/weather.csv`. Выполните задания по порядку.

In [96]:
def make_weather_csv(path, seed=0):
    """Генерирует синтетические наблюдения погоды и сохраняет их в CSV."""
    rng = np.random.default_rng(seed)
    dates = pd.date_range('2025-01-01', '2025-12-31', freq='D')
    base_temperatures = {'Тюмень': 2.0, 'Омск': 1.5, 'Томск': 0.5, 'Сочи': 15.0}
    frames = []
    for city, base_temperature in base_temperatures.items():
        season = -15 * np.cos(2 * np.pi * (dates.dayofyear.to_numpy() - 15) / 365)  # Минимум в середине января
        frames.append(pd.DataFrame({
            'city': city,
            'date': dates,
            'temperature': (base_temperature + season + rng.normal(0, 4, len(dates))).round(1),
            'precipitation': rng.exponential(1.5, len(dates)).round(1) * rng.integers(0, 2, len(dates)),
        }))
    pd.concat(frames, ignore_index=True).to_csv(path, index=False)


make_weather_csv(data_dir / 'weather.csv')

### Задание 1

Загрузите `data/weather.csv` в `DataFrame` `weather` (столбец `date` — как дату: параметр `parse_dates`). Посмотрите на данные через `head`, `info`, `describe`.

In [97]:
weather = ...

### Задание 2

Выберите дни, когда в Тюмени было теплее 20 градусов. Сколько таких дней?

### Задание 3

Добавьте столбец `month` с номером месяца (подсказка: `weather['date'].dt.month`) и посчитайте среднюю температуру и суммарные осадки по каждому городу. Какой город самый тёплый, какой — самый дождливый?

### Задание 4

Посчитайте среднюю температуру в Тюмени **дважды**:

1. циклом по строкам таблицы (`weather.iterrows()`);
2. векторной операцией pandas.

Убедитесь, что результаты совпадают, и сравните время через `%%timeit`.

# Решение

In [98]:
weather = pd.read_csv(data_dir / 'weather.csv', parse_dates=['date'])
weather.head()

     city       date  temperature  precipitation
0  Тюмень 2025-01-01        -12.1            1.5
1  Тюмень 2025-01-02        -13.2            0.0
2  Тюмень 2025-01-03        -10.1            0.0
3  Тюмень 2025-01-04        -12.3            0.0
4  Тюмень 2025-01-05        -14.9            1.5

In [99]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   city           1460 non-null   object
 1   date           1460 non-null   datetime64[ns]
 2   temperature    1460 non-null   float64
 3   precipitation  1460 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 45.8+ KB

In [100]:
weather.describe()

                                date  temperature  precipitation
count                           1460  1460.000000    1460.000000
mean   2025-07-01 23:59:59.999999744     4.535068       0.772192
min              2025-01-01 00:00:00   -23.300000       0.000000
25%              2025-04-02 00:00:00    -5.900000       0.000000
50%              2025-07-02 00:00:00     4.600000       0.000000
75%              2025-10-01 00:00:00    14.125000       1.100000
max              2025-12-31 00:00:00    36.500000      13.100000
std                              NaN    12.945722       1.349823

In [101]:
hot_days = weather[(weather['city'] == 'Тюмень') & (weather['temperature'] > 20)]
len(hot_days)

13

In [102]:
weather['month'] = weather['date'].dt.month
by_city = weather.groupby('city').agg(
    mean_temperature=('temperature', 'mean'),
    total_precipitation=('precipitation', 'sum'),
)
by_city

        mean_temperature  total_precipitation
city
Омск            1.189589                279.5
Сочи           14.854247                297.1
Томск           0.220274                270.1
Тюмень          1.876164                280.7

In [103]:
by_city['mean_temperature'].idxmax(), by_city['total_precipitation'].idxmax()

('Сочи', 'Сочи')

In [104]:
def mean_temperature_loop(weather, city):
    """Вычисляет среднюю температуру города циклом по строкам."""
    total = 0.0
    count = 0
    for _, row in weather.iterrows():
        if row['city'] == city:
            total += row['temperature']
            count += 1
    return total / count


def mean_temperature_vectorized(weather, city):
    """Вычисляет среднюю температуру города векторной операцией."""
    return weather.loc[weather['city'] == city, 'temperature'].mean()


mean_temperature_loop(weather, 'Тюмень'), mean_temperature_vectorized(weather, 'Тюмень')

(1.876164383561644, 1.8761643835616437)

In [105]:
%timeit -n 3 -r 3 mean_temperature_loop(weather, 'Тюмень')

46 ms ± 815 µs per loop (mean ± std. dev. of 3 runs, 3 loops each)

In [106]:
%timeit -n 3 -r 3 mean_temperature_vectorized(weather, 'Тюмень')

358 µs ± 38.1 µs per loop (mean ± std. dev. of 3 runs, 3 loops each)